eureka:
   client:
       serviceUrl:
           defaultZone: http://eureka:8095/eureka/
       register-with-eureka: true
       fetch-registry: true
      
management:
 security:
   enabled: false
   
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: subhammonitor@gmail.com
    password: subhambhai
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    mongodb:
      database: details
